function setLang(lang){document.body.classList.toggle('lang-es',lang==='es');document.body.classList.toggle('lang-en',lang==='en');document.querySelectorAll('.lang-btn').forEach(btn=>{btn.classList.toggle('active',btn.textContent.toLowerCase().startsWith(lang));});const cvDownload=document.getElementById('cv-download');if(cvDownload){cvDownload.href=lang==='en'?'cv/cv-en.pdf':'cv/cv-es.pdf';}}

document.querySelectorAll('.case-left').forEach(el=>el.classList.add('reveal','reveal-left'));
document.querySelectorAll('.case-right').forEach(el=>el.classList.add('reveal','reveal-right'));
document.querySelectorAll('.service-scene').forEach(el=>{if(el.querySelector('.right-middle')||el.querySelector('.hand-back-large')){el.classList.add('reveal','reveal-right');}else{el.classList.add('reveal','reveal-left');}});
document.querySelectorAll('.cards-box, .cv-box').forEach(el=>el.classList.add('reveal','reveal-scale'));
document.querySelectorAll('.section-title, .case-subtitle, .hero-logo-placeholder, .hero-title, .hero-subtitle').forEach(el=>el.classList.add('reveal','reveal-fade'));
const revealObserver=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');revealObserver.unobserve(entry.target);}});},{threshold:.15});
const revealElements=document.querySelectorAll('.reveal');revealElements.forEach(el=>revealObserver.observe(el));
function restartRevealAnimations(){revealObserver.disconnect();revealElements.forEach(el=>{el.classList.remove('in-view');});window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>{revealElements.forEach(el=>revealObserver.observe(el));},750);}document.querySelectorAll('.restart-animations').forEach(link=>{link.addEventListener('click',(e)=>{e.preventDefault();restartRevealAnimations();});});
const menu=document.querySelector('.site-menu');const toggle=document.querySelector('.menu-toggle');toggle.addEventListener('click',(e)=>{e.stopPropagation();menu.classList.toggle('open');});document.addEventListener('click',(e)=>{if(!menu.contains(e.target))menu.classList.remove('open');});
let index=0;function moveCarousel(dir){const track=document.getElementById('carousel-track');const total=track.children.length;index+=dir;if(index<0)index=total-1;if(index>=total)index=0;track.style.transform=`translateX(-${index*100}%)`;}
let mockupIndex=0;function moveMockupCarousel(dir){const track=document.getElementById('carousel-track-mockups');const total=track.children.length;mockupIndex+=dir;if(mockupIndex<0)mockupIndex=total-1;if(mockupIndex>=total)mockupIndex=0;track.style.transform=`translateX(-${mockupIndex*100}%)`;}
let socialIndex=0;function moveSocialCarousel(dir){const track=document.getElementById('carousel-track-social');const total=track.children.length;socialIndex+=dir;if(socialIndex<0)socialIndex=total-1;if(socialIndex>=total)socialIndex=0;track.style.transform=`translateX(-${socialIndex*100}%)`;}
let thumbnailIndex=0;function moveThumbnailCarousel(dir){const track=document.getElementById('carousel-track-thumbnails');const total=track.children.length;thumbnailIndex+=dir;if(thumbnailIndex<0)thumbnailIndex=total-1;if(thumbnailIndex>=total)thumbnailIndex=0;track.style.transform=`translateX(-${thumbnailIndex*100}%)`;}

let videoIndex=0;function moveVideoCarousel(dir){const track=document.getElementById('carousel-track-videos');const total=track.children.length;videoIndex+=dir;if(videoIndex<0)videoIndex=total-1;if(videoIndex>=total)videoIndex=0;track.style.transform=`translateX(-${videoIndex*100}%)`;}
